language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - ctest -V

script: make


