language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required

before_install:
  - if test "$TRAVIS_OS_NAME" = "linux"; then
        sudo apt-get update -q;
        sudo apt-get install cmake cmake-data g++ gcc libboost-all-devel
    fi

install:


