language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev python-pip
  - pip install cpplint

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - ctest -V
  - cd ..
  - cpplint --recursive . --exclude=build 



